export const ADMIN_LOADING = "ADMIN_LOADING";
export const ADMIN_ERROR = "ADMIN_ERROR";

export const GET_ADMIN_MENS_PRODUCT = "ADMIN_MENS_PRODUCT";
export const GET_ADMIN_WOMEMENS_PRODUCT = "ADMIN_WOMEMENS_PRODUCT";
export const GET_ADMIN_ALL_PRODUCT = "ADMIN_ALL_PRODUCT";
export const GET_ADMIN_USERS = "GET_ADMIN_USERS";
export const GET_ADMIN_ADMIN = "GET_ADMIN_ADMIN";
