export const ADMIN_LOADING = "ADMIN_LOADING";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const ADMIN_LOGIN = "ADMIN_LOGIN";


export const GET_ADMIN_MENS_PRODUCT = "ADMIN_MENS_PRODUCT";
export const GET_ADMIN_WOMEMENS_PRODUCT = "ADMIN_WOMEMENS_PRODUCT";
export const GET_ADMIN_ALL_PRODUCT = "ADMIN_ALL_PRODUCT";
export const GET_ADMIN_USERS = "GET_ADMIN_USERS";
export const GET_ADMIN_ADMIN = "GET_ADMIN_ADMIN";

export const TOGGLE_MEN = 'TOOGLE_MEN'
export const TOGGLE_WOMENMEN = 'TOOGLE_WOMENMEN'

export const PATCH_ADMIN_MENS_PRODUCT = "PATCH_ADMIN_MENS_PRODUCT";
export const PATCH_ADMIN_WOMEMENS_PRODUCT = "PATCH_ADMIN_WOMEMENS_PRODUCT";
export const PATCH_ADMIN_USERS = 'PATCH_ADMIN_USERS'
export const PATCH_ADMIN = 'PATCH_ADMIN'